import { registerTool } from '@toolbox/toolkit';

import { pdfMerge } from './pdf/merge.js';
import { pdfSplit } from './pdf/split.js';
import { pdfRotate } from './pdf/rotate.js';
import { pdfCompress } from './pdf/compress.js';
import { pdfMetadata } from './pdf/metadata.js';
import { imagesToPdf } from './pdf/images-to-pdf.js';
import { jsonPrettify } from './format/json-prettify.js';
import { jsonMinify } from './format/json-minify.js';
import { yamlPrettify } from './format/yaml-prettify.js';
import { xmlPrettify } from './format/xml-prettify.js';
import { sqlFormat } from './format/sql-format.js';
import { markdownPreview } from './format/markdown-preview.js';
import { base64Encode } from './crypto/base64-encode.js';
import { base64Decode } from './crypto/base64-decode.js';
import { hashGenerator } from './crypto/hash.js';
import { uuidGenerator } from './crypto/uuid.js';
import { urlEncode } from './crypto/url-encode.js';
import { urlDecode } from './crypto/url-decode.js';
import { jwtDecode } from './crypto/jwt-decode.js';
import { colorConvert } from './dev/color-convert.js';
import { regexTest } from './dev/regex-test.js';
import { queryString } from './dev/querystring.js';
import { byteConverter } from './dev/byte-converter.js';
import { zipCreate } from './archive/zip.js';
import { zipExtract } from './archive/unzip.js';
import { lineEndings } from './text/line-endings.js';
import { sortLines } from './text/sort-lines.js';
import { wordCount } from './text/word-count.js';
import { findReplace } from './text/find-replace.js';
import { caseConvert } from './text/case-convert.js';
import { removeDuplicates } from './text/remove-duplicates.js';
import { textDiff } from './diff/text-diff.js';
import { jsonDiff } from './diff/json-diff.js';
import { yamlDiff } from './diff/yaml-diff.js';
import { csvDiff } from './diff/csv-diff.js';
import { timestampConverter } from './time/timestamp.js';
import { cronParser } from './time/cron.js';
import { imageCompress } from './image/compress.js';
import { imageConvert } from './image/convert.js';
import { imageResize } from './image/resize.js';
import { imageCrop } from './image/crop.js';
import { imageStripExif } from './image/strip-exif.js';
import { imageRotate } from './image/rotate.js';

registerTool(pdfMerge);
registerTool(pdfSplit);
registerTool(pdfRotate);
registerTool(pdfCompress);
registerTool(pdfMetadata);
registerTool(imagesToPdf);
registerTool(jsonPrettify);
registerTool(jsonMinify);
registerTool(yamlPrettify);
registerTool(xmlPrettify);
registerTool(sqlFormat);
registerTool(markdownPreview);
registerTool(base64Encode);
registerTool(base64Decode);
registerTool(hashGenerator);
registerTool(uuidGenerator);
registerTool(textDiff);
registerTool(jsonDiff);
registerTool(yamlDiff);
registerTool(csvDiff);
registerTool(timestampConverter);
registerTool(cronParser);
registerTool(imageCompress);
registerTool(imageConvert);
registerTool(imageResize);
registerTool(imageCrop);
registerTool(imageStripExif);
registerTool(imageRotate);
registerTool(urlEncode);
registerTool(urlDecode);
registerTool(jwtDecode);
registerTool(zipCreate);
registerTool(zipExtract);
registerTool(lineEndings);
registerTool(sortLines);
registerTool(wordCount);
registerTool(findReplace);
registerTool(caseConvert);
registerTool(removeDuplicates);
registerTool(colorConvert);
registerTool(regexTest);
registerTool(queryString);
registerTool(byteConverter);
